/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: LostBoyz2078 (https://sketchfab.com/LostModels2025)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/mutant-animal-talk-5434e2f0b4ef41eda24e7d0b0b34ca6b
Title: Mutant Animal talk
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import scene from '../assets/3d/mutant_animal_talk.glb'



const Fox = ({ currentAnimation, ...props }) => {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(scene);
    const { actions } = useAnimations(animations, group);

    useEffect(() => {
        Object.values(actions).forEach((action) => action.stop());

        if (actions[currentAnimation]) {
            actions[currentAnimation].play();
        }
    }, [actions, currentAnimation])



    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="root">
                        <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                            <group name="GLTF_created_0">
                                <primitive object={nodes.GLTF_created_0_rootJoint} />
                                <skinnedMesh
                                    name="Object_7"
                                    geometry={nodes.Object_7.geometry}
                                    material={materials.MI_HonkyFace}
                                    skeleton={nodes.Object_7.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_10"
                                    geometry={nodes.Object_10.geometry}
                                    material={materials.MI_HonkyCloth}
                                    skeleton={nodes.Object_10.skeleton}
                                />
                                <group name="0000_Honky_91">
                                    <group name="0000_Honky_92" />
                                </group>
                                <group name="0001_Honky_93">
                                    <group name="0001_Honky_94" />
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    );
}

// useGLTF.preload("/mutant_animal_talk.glb");
export default Fox;
